import type { Metadata } from "next";
import { IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header/page";
import { Github } from "lucide-react"

const ibm = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">  
      <body
        className={`${ibm.className} antialiased bg-emerald-800 `}
      >
        <Header/>
        {children}
        <footer className="row-start-3 flex gap-[24px] flex-wrap items-center justify-center bg-emerald-900 min-h-10 ">
        <a
          className="flex items-center gap-2 hover:underline hover:underline-offset-4"
          href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Github
          />
          Github
        </a>
      </footer>
      </body>
    </html>
  );
}
